### Numpy

- Fast
    - complied using C, C++, Fortran
    - vectorized code
- Easy to perform mathematical operation (Linear Algebra)
- Express data as Matrix

#### 1. Matrix
- 1.1) Generate matrix: np.array, np.zeros, np.arange
- 1.2) Shape
- 1.3) Indexing

#### 2. Linspace / Logspace
- Linspace: returns the value of location or interval which was linearly divided
- Logspace: returns the value of location or interval whic was divided on a log scale

#### 3. Random
- 3.1) seed : a numerical value that generates a new set 
- 3.2) rand : generate random value with uniform distribution
- 3.3) randn :  generate random value with normal distribution
- 3.4) randint : generate random integer value with uniform distribution
- 3.5) suffle :  suffle the data of matrix
- 3.6) choice : select the data with specific probability

#### 4. Transpose / Concatenation

#### 5.  Add / Delete

#### 6. Statistical model
- 6.1) Basic stats
- 6.2) Variance
- 6.3) Covariance
- 6.4) Correlation Coefficient
- 6.5) cofficient of determination: R-squared

In [2]:
import numpy as np

In [13]:
# 1. Array
# np.array(object, dtype = None)

array = np.array([100, 200, 300])
print("type: ",type(array))
print(array)

intArray = np.array([1,2,3], dtype = int)
print(intArray)

floatArray = np.array([4,5,6], dtype = float)
print(floatArray)

complexArray = np.array([7,8,9], dtype = complex)
print(complexArray)

type:  <class 'numpy.ndarray'>
[100 200 300]
[1 2 3]
[4. 5. 6.]
[7.+0.j 8.+0.j 9.+0.j]


In [6]:
# initialize 
# np.zeros(size of matrix)

z1 = np.zeros((2,3)) # row = 2, col = 3
print(z1)

z2 = np.zeros(4)     # row = 1, col = 4
print(z2)


[[0. 0. 0.]
 [0. 0. 0.]]
[0. 0. 0. 0.]


In [12]:
# arrange
# np.arange(start, end, step, dtype)

ar1 = np.arange(5) 
print(ar1)

ar2 = np.arange(1,10,2)
print(ar2)

[0 1 2 3 4]
[1 3 5 7 9]


In [15]:
# other function

a1 = np.arange(12)
print(a1)
# ndarray.ndim -> number of dimension
print("ndim: ",a1.ndim)

# ndarray.shape -> (row, col)
# ndarray.reshape(row, col) -> new array

a2 = a1.reshape(3,4)
print(a2)
print(a2.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11]
ndim:  1
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
ndim:  1
(3, 4)


In [28]:
# indexing 
ls = np.array([[1,2,3], [4,5,6], [7,8,9]])
# select data
print(ls[0])
print(ls[0][1])
print(ls[0,1])
# modify data
ls[0][1] = 99
print(ls)
# broadcasting
ls[1] = 100
print(ls)
# slicing
ls2 = ls[1:]
print(ls2)

ls3 = ls[...,1:]
print(ls3)

[1 2 3]
2
2
[[ 1 99  3]
 [ 4  5  6]
 [ 7  8  9]]
[[  1  99   3]
 [100 100 100]
 [  7   8   9]]
[[100 100 100]
 [  7   8   9]]
[[ 99   3]
 [100 100]
 [  8   9]]


In [21]:
condition = ls%2 == 0
condition

array([[False, False, False],
       [ True,  True,  True],
       [False,  True, False]])

In [24]:
ls[condition] = 999
ls

array([[  1,  99,   3],
       [999, 999, 999],
       [  7, 999,   9]])

In [ ]:
import matplotlib.pyplot as plt
def namdelbrot(h,w,maxit=20, r=2):
    x = np.linspace(-2, 1.5, 4*h+1)
    y = np.linspace(-1.5, 1.5, 3*w+1)
    A, B = np.meshgrid(x,y)
    C = A + B*1j
    z = np.zeros_like(C)
    divtime = maxit + np.zeros(z.shape, dtype=int)
    
    for i in range(maxit):
        z = z**2 + C
        diverge = abs(z) > r
        div_now = diverage & (divtime == maxit)
        divtime[div_now] = i
        z[diverge]